name: pettingzoo.mpe.simple_tag_v3
n_episodes: 1000
episode_length: 250 # It should match with hyperparams max_cycles
n_rollout_threads: 1
hyperparams:
  render_mode: human
  num_good: 1
  num_adversaries: 3
  num_obstacles: 2
  continuous_actions: True
  max_cycles: 250
