name: MADDPGWrapper
agent_alg: MADDPG
adversary_alg: MADDPG
gamma: 0.953
tau: 0.013
lr: 0.013
hidden_dim: 643

n_exploration_eps: 2000
final_noise_scale: 0.0
init_noise_scale: 0.3
batch_size: 1024
n_rollout_threads: 1
steps_per_update: 100

explore: True

# replay buffer
buffer_length: 1e6