name: MATD3Wrapper
gamma: 0.95
tau: 0.01
hidden_dim: 64
min_action: -1
max_action: 1

lr_a: 5e-4
lr_c: 5e-4
use_orthogonal_init: True
use_grad_clip: True

policy_noise: 0.2
noise_clip: 0.5
policy_update_freq: 2

noise_std_init: 0.2
noise_std_min: 0.05
noise_decay_steps: 3e5
use_noise_decay: True 

n_exploration_eps: 2000
final_noise_scale: 0.0
init_noise_scale: 0.3
batch_size: 1024
n_rollout_threads: 1
steps_per_update: 100

# replay buffer
buffer_size: 1e6